language: ruby
sudo: false

rvm:
  - 2.5.3

before_install:
  - gem update --system
  - gem install bundler
  - cp config/database.yml.dist config/database.yml
  - cp .env-dist .env

install: bundle install --retry=3

notifications:
  email: false
