language: ruby
sudo: false

rvm:
  - 2.5.3

install: bundle install --retry=3

before_script:
    - cp config/database.yml.dist config/database.yml
    - cp .env-dist .env
    - bundle exec rake db:setup

services:
  - postgresql

notifications:
  email: false
